#!/bin/sh
echo "#block access to private address space" >> /etc/firewall.user
echo "iptables -I FORWARD -d 192.168.0.0/16 -j DROP" >> /etc/firewall.user
echo "iptables -I FORWARD -d 172.16.0.0/12 -j DROP" >> /etc/firewall.user
echo "iptables -I FORWARD -o eth+ -d 10.0.0.0/8 -j DROP" >> /etc/firewall.user

echo "#allow only SSH (rate limit) and (tinc) on WAN" >> /etc/firewall.user
echo 'wan=$(uci get qmp.interfaces.wan_devices)' >> /etc/firewall.user
echo 'iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT' >> /etc/firewall.user
echo 'iptables -A INPUT -p tcp --dport 22 -j ACCEPT -i $wan' >> /etc/firewall.user
echo '#iptables -A INPUT -p tcp --dport 655 -j ACCEPT -i $wan' >> /etc/firewall.user
echo '#iptables -A INPUT -p udp --dport 655 -j ACCEPT -i $wan' >> /etc/firewall.user
echo 'iptables -I INPUT -p tcp --dport 22 -i $wan -m state --state NEW -m recent --set' >> /etc/firewall.user
echo 'iptables -I INPUT -p tcp --dport 22 -i $wan -m state --state NEW -m recent  --update --seconds 60 --hitcount 4 -j DROP' >> /etc/firewall.user
echo 'iptables -A INPUT -j DROP -i $wan' >> /etc/firewall.user
